package com.banking.bms.enumerations;

import lombok.Getter;

@Getter
public enum PermissionEnum {

    USER_REGISTER,
    USER_LOGIN,
    USER_LOGOUT,
    ASSIGN_ROLES,

    VIEW_ROLE,

    USER_VIEW,
    USER_UPDATE,
    USER_DELETE,
    USER_LIST,

    ACCOUNT_CREATE,
    ACCOUNT_VIEW,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETE,

    TRANSACTION_DEPOSIT,
    TRANSACTION_WITHDRAW,
    TRANSACTION_TRANSFER,
    TRANSACTION_VIEW,

    LOAN_APPLY,
    LOAN_VIEW,
    LOAN_APPROVE,
    LOAN_REJECT,
    LOAN_STATUS_VIEW,

    AUDIT_LOG_VIEW,
    AUDIT_TRANSACTION_REVIEW,

    SUPPORT_TICKET_CREATE,
    SUPPORT_TICKET_VIEW,
    SUPPORT_TICKET_UPDATE
}
